### ISSUE TITLE
预备课chroot实验部分文档错误

### ISSUE THREAD

**Issue by robincoin** [jolestar/kubernetes-complete-course#1]
chroot实验部分文档错误:
# 恢复回来
cp /var/lib/xocker/image/busybox.bak /var/lib/xocker/image/busybox

这里少了-r应该是下面这样:
cp -r /var/lib/xocker/image/busybox.bak /var/lib/xocker/image/busybox

**Comment by jolestar** [comment]
感谢，已经修复。
