### ISSUE TITLE
Can't request key from hkp server p80.pool.sks-keyservers.net

### ISSUE THREAD

**Issue by jerryjedi** [jolestar/kubernetes-complete-course#2]
When execute "apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D" in QingCloud SH1, got a error message:
![image](https://user-images.githubusercontent.com/7875026/31265622-5bd8b6e8-aaa2-11e7-9ee5-4db78fadeaa7.png)

**Comment by jolestar** [comment]
@jerryjedi  please ensure your host can access network, and retry.

**Comment by jerryjedi** [comment]
The VM can access internet. I can do the "apt-get update" and also "ping www.qingcloud.com". When I execute "apt-get install -y ebtables socat apt-transport-https bash-completion ntp wget",it's successful.

**Comment by jolestar** [comment]
<img width="936" alt="screen shot 2017-10-30 at 10 53 44" src="https://user-images.githubusercontent.com/77268/32152807-2d019a3e-bd61-11e7-96df-69afd877949e.png">

I try this command again on qingcloud pek3a, it is success. You can try to use https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-using-the-repository this guide to install  docker.
