### ISSUE TITLE
Error loading media: File could not be played

### ISSUE THREAD

**Issue by liketic** [jolestar/kubernetes-complete-course#3]
I tried chrome and safari, both of them can not play the video. I think it's a bug of CSDN.

**Comment by jolestar** [comment]
csdn need flash player. you can try mobile app.

**Comment by liketic** [comment]
@jolestar Thanks.

**Comment by ghost** [comment]
@jolestar but app of csdn has so many bugs , just like crash.

**Comment by liketic** [comment]
@jolestar I'd like to suggest http://study.163.com/ ... 😄
