### ISSUE TITLE
请教您一个问题，pod不能访问外部网络，可以怎么去排查呢？

### ISSUE THREAD

**Issue by zouhuigang** [jolestar/kubernetes-complete-course#6]
就是我有一个服务，需要发送短信，试了下，在pod里面发不出请求。

**Comment by zouhuigang** [comment]
已经解决了

**Comment by jolestar** [comment]
@zouhuigang 是否方便描述下排查过程以及结果？方便别人参考。

**Comment by zouhuigang** [comment]
@jolestar 好的，闹了半天是因为没有安装kube-dns服务，pod里面访问公网的过程是:

    pod->dns解析域名，得到ip地址->docker0网卡->iptables` nat->公网

开始一直以为是出在docker0网卡和iptables上，然后设置了:

    iptables -t nat -I POSTROUTING -s 10.254.3.0/24 -j MASQUERADE 

还是无效，经过询问，才知道kube-dns没装的话，对pod是有影响的。经过在pod里面测试，发现使用ip地址是可以访问外网，所以最后确定问题出在域名解析上了。
